var data = [
    {
        "id": 34,
        "title": "IKEA Table 宜家拉克方桌",
        "desc": "",
        "price": 5,
        "category": ["furniture"],
        "sold": true,
    },
    {
        "id": 35,
        "title": "IKEA memory foam pilow (2 pieces) 宜家枕芯两个送原装枕套",
        "desc": "",
        "price": 10,
        "category": ["misc"],
        "sold": true,
    },
    {
        "id": 1,
        "title": "IKEA Artist's Figure 宜家小人",
        "desc": "",
        "price": 2,
        "category": ["stationary"],
        "sold": false,
    },
    {
        "id": 45,
        "title": "IKEA storage unit 宜家可移动大容量储物架",
        "desc": "",
        "price": 12,
        "category": ["furniture"],
        "sold": false,
    },
    {
        "id": 46,
        "title": "Sharp Aquos 55’ 4K smart tv 夏普电视55寸",
        "desc": "Sharp LC-55P6000U, only $140 if pick up in May",
        "price": 190,
        "category": ["appliance"],
        "sold": true,
    },
    {
        "id": 47,
        "title": "Futon 现代风沙发床",
        "desc": "original price 230，only $90 if pick up in May",
        "price": 130,
        "category": ["furniture"],
        "sold": true,
    },
    {
        "id": 48,
        "title": "TV stand/storage unit 电视柜/储物柜",
        "desc": "original price 79",
        "price": 38,
        "category": ["furniture"],
        "sold": true,
    },
    {
        "id": 36,
        "title": "IKEA MULIG shelf unit 宜家储物架/书架",
        "desc": "available after May 10th, original price 39.99",
        "price": 18,
        "category": ["furniture"],
        "sold": true,
    },
    {
        "id": 37,
        "title": "IKEA Draget shelf unit 宜家储物架/书架",
        "desc": "available after May 10th, original price 29.99",
        "price": 15,
        "category": ["furniture"],
        "sold": false,
    },
    {
        "id": 38,
        "title": "Acer Chromebook N15Q8 上网本",
        "desc": "used for 1 year, original price 200",
        "price": 85,
        "category": ["electronics"],
        "sold": false,
    },
    {
        "id": 39,
        "title": "Magnet Blocks 40 pcs 磁铁玩具",
        "desc": "",
        "price": 5,
        "category": ["kid"],
        "sold": true,
    },
    {
        "id": 31,
        "title": "Mainstay Table and Chairs 餐桌餐椅一套",
        "desc": "link: https://bit.ly/2IL0xWg",
        "price": 48,
        "category": ["util"],
        "sold": true,
    },
    {
        "id": 42,
        "title": "Logitech multi-device bluetooth keyboard 罗技蓝牙键盘",
        "desc": "comes with batteries",
        "price": 15,
        "category": ["electronics"],
        "sold": false,
    },
    {
        "id": 32,
        "title": "4-in-1 Crib 婴儿床送床垫，床单，透气围栏",
        "desc": "link: https://tinyurl.com/y2vlol7n, comes with free mattress, sheet, mesh liner",
        "price": 60,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 2,
        "title": "White Board with Magnet 白板",
        "desc": "40cm * 60cm",
        "price": 2,
        "category": ["stationary"],
        "sold": true,
    },
    {
        "id": 3,
        "title": "Health O Meter Baby Toddler Scale 婴儿秤",
        "desc": "",
        "price": 10,
        "category": ["kid"],
        "sold": true,
    },
    {
        "id": 4,
        "title": "Spiderman Drone 蜘蛛侠遥控玩具",
        "desc": "package not opened, original price $60",
        "price": 30,
        "category": ["kid"],
        "sold": true,
    },
    {
        "id": 5,
        "title": "Big Black Fan 大扇子",
        "desc": "free with other purchases",
        "price": 0,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 6,
        "title": "Lego Classic 乐高",
        "desc": "package not opened, original price $27",
        "price": 15,
        "category": ["kid"],
        "sold": true,
    },
    {
        "id": 7,
        "title": "Tao Tronics Ultrasonic Humidifier 加湿器",
        "desc": "1.35 gallon, cool mist, no need for any maintenance, very quiet",
        "price": 20,
        "category": ["appliance"],
        "sold": true,
    },
    {
        "id": 8,
        "title": "HomeLabs Dish Washer 洗碗机",
        "desc": "link: https://tinyurl.com/y5fueshk",
        "price": 65,
        "category": ["appliance"],
        "sold": false,
    },
    {
        "id": 9,
        "title": "Computer Desk - L shape L型电脑桌",
        "desc": "will deliver and assemble for free",
        "price": 58,
        "category": ["furniture"],
        "sold": true,
    },
    {
        "id": 10,
        "title": "Munchkin Drying Rack 奶瓶晾干架",
        "desc": "",
        "price": 3,
        "category": ["baby"],
        "sold": false,
    },
    {
        "id": 11,
        "title": "Blackout Shades 100% 遮光窗帘(还剩一个)",
        "desc": "size fits Kraettli windows",
        "price": 3,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 12,
        "title": "Car Seat Cover 安全座椅防风套",
        "desc": "original price - 35",
        "price": 10,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 13,
        "title": "Bathtub for Baby 宝宝浴盆",
        "desc": "",
        "price": 5,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 14,
        "title": "SkipHop Changing Station 便携尿布垫/包",
        "desc": "",
        "price": 5,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 15,
        "title": "Xiaomi Portable Phone Charger 小米充电器",
        "desc": "10400mh",
        "price": 5,
        "category": ["electronics"],
        "sold": false,
    },
    {
        "id": 16,
        "title": "Newborn Socks 新生儿袜",
        "desc": "0m",
        "price": 0,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 17,
        "title": "Baby Socks 婴儿袜",
        "desc": "0-3m",
        "price": 0,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 18,
        "title": "Changing Pacd Cover 尿布台遮罩",
        "desc": "",
        "price": 1,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 19,
        "title": "Bobby Head Support 婴儿头垫",
        "desc": "",
        "price": 2,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 20,
        "title": "Bottle Warmer 温奶器",
        "desc": "",
        "price": 6,
        "category": ["baby"],
        "sold": false,
    },
    {
        "id": 21,
        "title": "Portable Phone Charger 手机充电器",
        "desc": "10000mh",
        "price": 5,
        "category": ["electronics"],
        "sold": false,
    },
    {
        "id": 22,
        "title": "Massager 按摩器",
        "desc": "",
        "price": 15,
        "category": ["electronics"],
        "sold": false,
    },
    {
        "id": 29,
        "title": "Rock n' Play 婴儿电动摇篮",
        "desc": "with a selection of soothing music, original price $60",
        "price": 20,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 23,
        "title": "Braun Forehead Thermometer 额温计",
        "desc": "BFH125",
        "price": 10,
        "category": ["baby", "electronics"],
        "sold": true,
    },
    {
        "id": 24,
        "title": "Stapler 订书机",
        "desc": "comes with staples",
        "price": 2,
        "category": ["stationary"],
        "sold": true,
    },
    {
        "id": 25,
        "title": "Lock 锁",
        "desc": "",
        "price": 1,
        "category": ["stationary"],
        "sold": true,
    },
    {
        "id": 26,
        "title": "Catan 桌游-卡坦岛",
        "desc": "",
        "price": 15,
        "category": ["game"],
        "sold": false,
    },
    {
        "id": 27,
        "title": "Catan Expansion 卡坦岛扩展",
        "desc": "package open, but never played",
        "price": 15,
        "category": ["game"],
        "sold": false,
    },
    {
        "id": 28,
        "title": "Baby Bath Cushion 新生儿洗澡垫",
        "desc": "",
        "price": 0,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 30,
        "title": "Shopping Cart 购物/洗衣推车",
        "desc": "",
        "price": 6,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 33,
        "title": "Baby Fence 婴儿防护栏",
        "desc": "",
        "price": 35,
        "category": ["baby"],
        "sold": true,
    },
    {
        "id": 40,
        "title": "Iron",
        "desc": "",
        "price": 1,
        "category": ["misc"],
        "sold": true,
    },
    {
        "id": 41,
        "title": "Conair hair clipper set 理发器",
        "desc": "giveaway",
        "price": 0,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 43,
        "title": "fabric fuzz remover 衣物除毛器",
        "desc": "",
        "price": 0,
        "category": ["misc"],
        "sold": true,
    },
    {
        "id": 44,
        "title": "knee pads 护膝",
        "desc": "new",
        "price": 1,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 49,
        "title": "printing paper 300 sheets 打印纸约300张",
        "desc": "package open, half used",
        "price": 2,
        "category": ["stationary"],
        "sold": false,
    },
    {
        "id": 50,
        "title": "jQuery教程",
        "desc": "",
        "price": 0,
        "category": ["book"],
        "sold": false,
    },
    {
        "id": 51,
        "title": "JavaScript教程",
        "desc": "",
        "price": 0,
        "category": ["book"],
        "sold": false,
    },
    {
        "id": 52,
        "title": "jQuery Cookbook",
        "desc": "",
        "price": 0,
        "category": ["book"],
        "sold": false,
    },
    {
        "id": 53,
        "title": "Cracking the Coding Interview 刷题书",
        "desc": "",
        "price": 5,
        "category": ["book"],
        "sold": false,
    },
    {
        "id": 54,
        "title": "hp printer 惠普打印机",
        "desc": "out of black&white ink",
        "price": 2,
        "category": ["stationary"],
        "sold": false,
    },
    {
        "id": 55,
        "title": "ikea magazine file 宜家书立",
        "desc": "https://www.ikea.com/us/en/catalog/products/10395416/",
        "price": 2,
        "category": ["book"],
        "sold": false,
    },
    {
        "id": 56,
        "title": "fidget spinner",
        "desc": "",
        "price": 0,
        "category": ["kid"],
        "sold": false,
    },
    {
        "id": 57,
        "title": "Coleman Stainless Steel Thermal Bottle 保温杯",
        "desc": "very large size, only used as a container to keep warm water, never drank from it",
        "price": 4,
        "category": ["kitchen"],
        "sold": false,
    },
    {
        "id": 58,
        "title": "travel pillow 旅行枕",
        "desc": "the cover can be taken off and washed separately",
        "price": 2,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 59,
        "title": "ikea tools 宜家工具",
        "desc": "available after May 15th, 2019",
        "price": 10,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 60,
        "title": "AC pro 汽车空调氟利昂",
        "desc": "original price $33. Instant cooling, half a bottle left, with easy to add charging hose and gauge",
        "price": 12,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 61,
        "title": "shredder",
        "desc": "available after May 15th, 2019",
        "price": 8,
        "category": ["stationary"],
        "sold": false,
    },
    {
        "id": 62,
        "title": "baby pic frame 宝宝相框(能站立)",
        "desc": "free",
        "price": 0,
        "category": ["baby"],
        "sold": false,
    },
    {
        "id": 63,
        "title": "slow cooker 慢炖锅",
        "desc": "6 qt",
        "price": 5,
        "category": ["kitchen"],
        "sold": false,
    },
    {
        "id": 64,
        "title": "Cetaphil Skin Cleanser 洗面奶",
        "desc": "used only once. was a gift from a friend so I'm giving it away for free",
        "price": 0,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 65,
        "title": "scale 体重秤",
        "desc": "",
        "price": 3,
        "category": ["misc"],
        "sold": false,
    },
    {
        "id": 66,
        "title": "Casio Calculator 卡西欧计算器",
        "desc": "",
        "price": 10,
        "category": ["stationary"],
        "sold": false,
    },
    {
        "id": 67,
        "title": "USB desk fan 桌面小电扇USB接口",
        "desc": "",
        "price": 3,
        "category": ["electronics"],
        "sold": false,
    },
    {
        "id": 68,
        "title": "ikea TERTIAL desk lamp",
        "desc": "https://www.ikea.com/us/en/catalog/products/60424987/",
        "price": 10,
        "category": ["stationary"],
        "sold": false,
    },
    {
        "id": 69,
        "title": "resistance band (5kg)",
        "desc": "",
        "price": 2,
        "category": ["sports"],
        "sold": false,
    },
    {
        "id": 70,
        "title": "resistance band(8kg)",
        "desc": "",
        "price": 0,
        "category": ["sports"],
        "sold": false,
    },
    {
        "id": 71,
        "title": "tennis racket * 2",
        "desc": "https://www.ikea.com/us/en/catalog/products/60424987/",
        "price": 5,
        "category": ["sports"],
        "sold": false,
    },
    {
        "id": 72,
        "title": "wrist sling 弹弓",
        "desc": "",
        "price": 1,
        "category": ["sports"],
        "sold": false,
    },
];